## **DAY 1**. . . . . . *0:00:00*
VIDEO  https://www.youtube.com/watch?v=V_xro1bcAuA

COURSE https://www.learnpytorch.io/

DOCS   https://pytorch.org/docs/stable/index.html

GITHUB https://github.com/mrdbourke/pytorch-deep-learning

### HELLO WORLD AND LIBRARIES


In [ ]:
var = "world !"
print("Hello "+ var)

Hello world !


In [ ]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


In [ ]:
import torch as torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.0+cu118


In [ ]:
## introduction  to tensors

### Creating a tensor

### INTRODUCTION TO TENSORS

 Creating a tensor
 we use # to format text
pytorch tensors are created using torch.tensor()
https://pytorch.org/docs/stable/tensors.html

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as python int
scalar.item()

7

In [ ]:
#vector 
vector = torch.tensor([7,8])
print(vector.ndim)  # Tensor dimension.......Num=0 Vec=1 Matrix=2
print(vector.shape) # vector dimension  2
vector

1
torch.Size([2])


tensor([7, 8])

In [ ]:
# Matrix
MATRIX = torch.tensor( [ [1,2],[3,4] ] )   # vector matri

print(MATRIX.ndim)    #  2
print(MATRIX.shape)   #  2x2
MATRIX                #  [1,2][3,4]

2
torch.Size([2, 2])


tensor([[1, 2],
        [3, 4]])

### DATA NAME CONVENTION
  https://www.learnpytorch.io/00_pytorch_fundamentals/#:~:text=it%20actually%20is.-,Let%27s%20summarise.,-Name


In [ ]:
# Tensor
TENSOR = torch.tensor([  [[1,2,3],[3,4,5],[6,7,8]]  ])
print(TENSOR.ndim)    # 3
print(TENSOR.shape)   # 1x3x3
TENSOR = torch.tensor([  [[1,2] , [3,4]] ,
                         [[5,6] , [7,8]] ,
                        [[9,10] , [11,12]] , ] )
print(TENSOR.shape)   # 3x2x2
TENSOR = torch.tensor( [ [  [[1] , [2]] , [[3] , [4]] ] ,
                         [  [[5] , [6]] , [[7] , [8]] ]  ])
print(TENSOR.ndim)    # 4
print(TENSOR.shape)   # 2x2x2x1


3
torch.Size([1, 3, 3])
torch.Size([3, 2, 2])
4
torch.Size([2, 2, 2, 1])


### 14 CREATING TENSORS

### RANDOM TENSOR
 Wny ?  cause we need them as a starting point for weight & bias
 then we adjust to a usefull value

In [ ]:
# Create Random Tensor size (2,2,1)
random_tensor = torch.rand(2,2,1)  # matrix hence lowecase
print(random_tensor.ndim)    # 3
print(random_tensor.shape)   # 2x2x1

# Create Random Tensor size (3x4)
random_tensor = torch.rand(3,4)  # matrix hence lowecase
print(random_tensor.ndim)    # 2
print(random_tensor.shape)   # 3x4

random_tensor

3
torch.Size([2, 2, 1])
2
torch.Size([3, 4])


tensor([[0.7576, 0.5931, 0.9244, 0.9657],
        [0.1456, 0.2428, 0.8750, 0.8464],
        [0.1686, 0.5302, 0.3293, 0.4031]])

#### IMAGE AND CHANNELS 
  https://www.learnpytorch.io/00_pytorch_fundamentals/#:~:text=dimensions%2C%20one%20for-,colour_channels,-%2C%20height%20and

In [ ]:
random_image_size_tensor = torch.rand(size=(3,224,224)) # Color-channels 3=RGB, Heigh, Width
random_image_size_tensor.shape, random_image_size_tensor.ndim
random_image_size_tensor

tensor([[[0.6891, 0.2152, 0.9073,  ..., 0.3127, 0.5685, 0.1836],
         [0.5358, 0.4695, 0.8563,  ..., 0.6610, 0.3255, 0.0840],
         [0.8212, 0.8823, 0.2974,  ..., 0.0881, 0.6355, 0.0890],
         ...,
         [0.5017, 0.0148, 0.5076,  ..., 0.0239, 0.7365, 0.4867],
         [0.0821, 0.2940, 0.0309,  ..., 0.2765, 0.6045, 0.8872],
         [0.9672, 0.8774, 0.1137,  ..., 0.6508, 0.0992, 0.4248]],

        [[0.9483, 0.2931, 0.0622,  ..., 0.7160, 0.9716, 0.1666],
         [0.2315, 0.2362, 0.2201,  ..., 0.0548, 0.6583, 0.6021],
         [0.2912, 0.9293, 0.9766,  ..., 0.0651, 0.1499, 0.5629],
         ...,
         [0.0806, 0.7623, 0.6983,  ..., 0.0012, 0.5895, 0.4706],
         [0.7178, 0.5013, 0.5805,  ..., 0.9380, 0.8201, 0.6588],
         [0.0410, 0.8910, 0.6348,  ..., 0.3538, 0.8478, 0.7350]],

        [[0.9169, 0.4372, 0.0779,  ..., 0.2000, 0.8651, 0.9349],
         [0.7978, 0.7198, 0.2356,  ..., 0.3008, 0.5114, 0.4386],
         [0.5521, 0.6739, 0.2580,  ..., 0.3464, 0.5703, 0.

### ZEROS & ONES . . . . .  1:46:00

In [ ]:
zeros = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))
print(zeros)
print(ones)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
ones*random_tensor


tensor([[0.7576, 0.5931, 0.9244, 0.9657],
        [0.1456, 0.2428, 0.8750, 0.8464],
        [0.1686, 0.5302, 0.3293, 0.4031]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### DATATYPES. . . . .  1:48:00

In [ ]:
ones.dtype #torch.float32 

torch.float32

### Range. . . . .  1:48:00
  https://pytorch.org/docs/stable/generated/torch.arange.html

In [ ]:
one_to_ten = torch.arange(0,11,1) # start=0, end=11, step=1
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### TENSORLIKE. . . . .  1:48:00

In [ ]:
ten_zeros = torch.zeros_like( input= one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None   # default dtype = torch.float32
                                            ,device=None  # device of our tensor
                                            ,requires_grad=False) # if we are tracking gradients with tensor operations
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype = torch.float16)
float_32_tensor.dtype

torch.float16

### 17 TENSOR DATATYPES
https://pytorch.org/docs/stable/tensors.html
  * One of 3 main miss-match Errors
1. wrong DATATYPE
2. wrong SHAPE
3. wrong DEVICE

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16) # TYPE CONVERSION ... torch.float16 = torch.half
float_16_tensor * float_32_tensor                    # DATATYPE MISMATCH  no error WTF !

tensor([ 9., 36., 81.], dtype=torch.float16)

#### LETS TRY WITH INTEGGER

In [ ]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
int_32_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

2:07:23 GO TO SLEEP WE'LL GET EM NEXT TIME !

# **DAY 2**. . . . . . *2:03:00*

In [ ]:
import torch as torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### 18 TENSOR ATRIBUTES
GETINF INFO FROM TENSORS

In [ ]:
some_tensor = torch.rand(3,4)
print(f"Datatype of tensor: {some_tensor.dtype}")  # torch.float32
print(f"Shape    of tensor: {some_tensor.shape}")  # 3,4
print(f"Devide   of tensor: {some_tensor.device}") # CPU / GPU

# some_tensor = torch.tensor([3,6,9],dtype=torch.long
                                    #,device=torch.gpu)
# print(f"Datatype of tensor: {some_tensor.dtype}")  torch.float32
# print(f"Shape    of tensor: {some_tensor.shape}")  # 3x4
# print(f"Devide   of tensor: {some_tensor.device}") # CPU / GPU

## 19 MANIPULATING TENSORS
https://youtu.be/V_xro1bcAuA&t=2hy14m

OPERATIONS
*   Adition substraction    (elementWise)
*   Multiplication Division (elementWise)
*   Matrix multiplication    row*col

In [ ]:
tensor = torch.tensor([1,2,3])  # 1*3
print(tensor + 10)  # every element x = x+10 
print(tensor - 10) 
print(tensor * 10)  # Python version
print(tensor / 2)

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.5000, 1.0000, 1.5000])


https://youtu.be/V_xro1bcAuA&t=2hy16m

In [ ]:
print(torch.add(tensor,10)) # PyTorch versions
print(torch.sub(tensor,10)) #
print(torch.mul(tensor,10)) # 
print(torch.div(tensor,2))  # 

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.5000, 1.0000, 1.5000])


## 20 MATRIX OPARATION
most common operation in Neu-Net
https://rajatvd.github.io/Factor-Graphs/
https://www.mathsisfun.com/algebra/matrix-multiplying.html 

https://medium.com/analytics-vidhya/tensordot-explained-6673cfa5697f

4D Trigonometry https://www.youtube.com/watch?v=Hx0rTKlVi8Y

In [ ]:
 # dot product (matrix multiplication)
 print(tensor, "*",tensor)
 print(f"ewuals {tensor * tensor}")
 torch.matmul(tensor,tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
ewuals tensor([1, 4, 9])


tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]* tensor[i]
print(value)

tensor(14)
CPU times: user 400 µs, sys: 932 µs, total: 1.33 ms
Wall time: 1.11 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 73 µs, sys: 0 ns, total: 73 µs
Wall time: 76.1 µs


tensor(14)

### 21 Matrix multiplication part 2 
https://www.youtube.com/watch?v=V_xro1bcAuA&t=2h28m
Shape Errors
*   (3x2)*(2x4) = 3x4
*   (3x2)*(3x2) = Error
*   (AxB)*(BxC) required shape


In [ ]:
%%time
torch.matmul(torch.rand(3,2),torch.rand(2,1)).shape          # 3, 1
torch.matmul(torch.rand(2,3,4),torch.rand(2,4,1)).shape      # 2, 3,1
torch.matmul(torch.rand(2,3,4,5),torch.rand(2,3,5,1)).shape  # 2, 3, 4, 1



CPU times: user 1.76 ms, sys: 0 ns, total: 1.76 ms
Wall time: 1.46 ms


torch.Size([2, 3, 4, 1])

We want to do this http://matrixmultiplication.xyz/
### 22 MATRIX MULTIPLICARION
https://www.youtube.com/watch?v=V_xro1bcAuA&t=2h35m


In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
# mm()= matmul()
torch.mm(tensor_A, tensor_B.T) # we transposed B to avoid miss-match shape

In [ ]:
print(tensor_B.T)
print(tensor_B.shape)  # transpose only creates a new instance
tensor_B

## 23 FIND MIN MAX MEAN & SUM of TENSOR
https://www.youtube.com/watch?v=V_xro1bcAuA&t=2h48m

In [ ]:
#create tensor
x = torch.arange(0, 100,10)
y = torch.arange(10,110,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.max(x)

tensor(90)

In [ ]:
torch.min(x)

tensor(0)

In [ ]:
x=x.type(torch.float32) # mean() cant use torch.int dtype
#  torch.mean(x)  
x.mean()

tensor(45.)

In [ ]:
x.add(y)

tensor([ 10,  30,  50,  70,  90, 110, 130, 150, 170, 190])

## 24 TENSOR AGREGATION

https://www.youtube.com/watch?v=V_xro1bcAuA&t=2h54m30s

find positional min max

In [ ]:
x.argmin() # index of min position

tensor(0)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
y = torch.tensor( [ [[9,8],[7,6]],
                    [[5,4],[3,2]] ] )
y.argmin() # y[7] = y[2][2][2]

tensor(7)

## 25 RESHAPING STACKING SQUEEZING
reshape =  change tensor shape

view = changes shape for same data example .T (transpose)

stack = cambine multiple tensors on top of eachoter (higher dim), vstack, hstack

squeeze =removes al [1] dimansions from tensor

unsqueeze = adds a [1] dimension 

permute = return a view of input with dimensions swap
https://www.youtube.com/watch?v=V_xro1bcAuA&t=2h55m50s

In [ ]:
import torch as torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
x = torch.arange(1.,10.,1)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# x_resh = x.reshape(3,9)  shape product must be same 3*9 != 9 = 3*3
x_resh = x.reshape(3,3)
print(x_resh)
x_resh = x.reshape(1,9)
x_resh

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

### **VIEW**

In [ ]:
# returning the view of x to z 
z = x.view(1,9)
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# changing z values changes x values but not shape
# because a view of a tensor shares same memory as original one
print(x)
z=z.reshape(3,3)
print(z)
z[:,2]=11         # change every element in last col 0,1,[2] to 11
z[1,1]=0          # change element[5] = col 1 row 1 to 0
#z[5]=0             same result
print(z)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([[ 1.,  2., 11.],
        [ 4.,  0., 11.],
        [ 7.,  8., 11.]])
tensor([[ 1.,  2., 11.],
        [ 4.,  0., 11.],
        [ 7.,  8., 11.]])


tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

### **STACK**

In [ ]:
# stack tensors on top of eachother
x_stack = torch.stack([x,x,x,x],dim=0) #dedault dim=0
x_stack

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
print(x_resh      )
print(x_resh.shape)
x_squez=x_resh.squeeze() # method .squeeze() eliminates dim=1
print( x_squez      ) 
print( x_squez.shape )   # atribute .shape   needs no parantesis
x_unsq = x_squez.unsqueeze(dim=0)


tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
torch.Size([1, 9])
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
torch.Size([9])


In [ ]:
x = torch.rand(2,3,5) # original dim index 0, 1, 2  valuues 2, 3, 5
print(x.size())       # dim index 0:col 1:row 2:depht
z=torch.permute(x,(2,0,1))  # returns view of original tensor
print(z.size())             # with interchanged dim order  to 2 0 1
print(x.size()) # does not change original tensor

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
torch.Size([2, 3, 5])


In [ ]:
z = torch.arange(0,8,1)
z = torch.reshape(z,[2,2,2])
print(z)
z = torch.permute(z,(2,1,0))  # 0:col & 2:depht interchanged
print(z)

tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])
tensor([[[0, 4],
         [2, 6]],

        [[1, 5],
         [3, 7]]])


https://eli.thegreenplace.net/2015/memory-layout-of-multi-dimensional-arrays

Name for dimentions


https://youtu.be/V_xro1bcAuA&t=3hy23m30s 

went to sleep 

#DAY 3 27 SELECTING DATA fromTENSOR

indexing with pythorch is similar to numpy


In [ ]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
print(x)
print(x[:][0]) # x[0] when max idex is 0 [:] is ignored
print(x[0][0]) # x[0,0] first row
print(x[0,0,0]) # x[0,0,0] forst element

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)


In [ ]:
print(x[0,0,:]) # row [0] = evey element last dim=2
print(x[0,:,0]) # col [0] = evey element penultim dim=1
print(x[0,:,:]) # x[0] first matrix

tensor([1, 2, 3])
tensor([1, 4, 7])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [ ]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) 
                        # convets from Numpy to Torch
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
print(array.dtype ) # float64 np array)
print(tensor.dtype) # float64 torch ensor
tensor = torch.from_numpy(array).type(torch.float32)
tensor.dtype        # conert do default dtype foat32

float64
torch.float64


torch.float32

In [ ]:
array = array + 1  # from_numpy makes a copy of array
array , tensor     # tensor doesnt change

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

https://youtu.be/V_xro1bcAuA&t=3h40m
https://pytorch.org/tutorials/beginner/examples_tensor/polynomial_numpy.html

## 29 REPRODUCIBILITY
* start random numbers 
* tensor operations
* update numbers to adjust to data
* repeat process

reduce same "random" outcome = reproducibility

https://pytorch.org/docs/stable/notes/randomness.html

to redice randomness we use same SEED hence same "random" values

In [ ]:
import torch
RANDOM_SEED = 21121994
torch.manual_seed(RANDOM_SEED)

rand_a =torch.rand(3,4)
rand_b =torch.rand(3,4)
print(rand_a)
print(rand_b)
print(rand_a == rand_b) 

torch.manual_seed(RANDOM_SEED) # RESET SEED
#same vaues as previous exampe
rand_c =torch.rand(3,4)
rand_d =torch.rand(3,4)
print(rand_c)
print(rand_c)
print(rand_a == rand_c) 

tensor([[0.8214, 0.3550, 0.2988, 0.4180],
        [0.4666, 0.8903, 0.7180, 0.5552],
        [0.8766, 0.8868, 0.1002, 0.6008]])
tensor([[0.2911, 0.8045, 0.1991, 0.7702],
        [0.4031, 0.7608, 0.8120, 0.8189],
        [0.5743, 0.2497, 0.4035, 0.5814]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
tensor([[0.8214, 0.3550, 0.2988, 0.4180],
        [0.4666, 0.8903, 0.7180, 0.5552],
        [0.8766, 0.8868, 0.1002, 0.6008]])
tensor([[0.8214, 0.3550, 0.2988, 0.4180],
        [0.4666, 0.8903, 0.7180, 0.5552],
        [0.8766, 0.8868, 0.1002, 0.6008]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## 30 different ways acces GPU in PyTorch

GPU makes faster computation on numbers 

thanks to cuda + nvidia hardware  
## options
* Colab & colab pro
* your own GPU (needs pytorch cuda setup)https://pytorch.org/get-started/locally/
* Cloud : GCP AWS Azure and others services

In [ ]:
  !nvidia-smi # Tesla T4  https://technical.city/en/video/Tesla-K80-vs-Tesla-T4

Tue Apr 11 04:58:28 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
#check for gpu acces
import torch
torch.cuda.is_available() #true

True

setupp device agnostic code

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device #CUDA  when entorno trabajo =GPU
torch.cuda.device_count() #1

1

DEVICE AGOSTIC CODE 

https://pytorch.org/docs/stable/notes/cuda.html

## 31 SETING UP DEVISE AGNOSTIC CODE

https://www.youtube.com/watch?v=V_xro1bcAuA&t=4h5m

In [ ]:
import torch as torch
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device) #CUDA  when entorno trabajo =GPU
torch.cuda.device_count() #1

cuda


1

In [ ]:
tensor = torch.tensor([1,2,3]) #tensor not on GPU
print(tensor, tensor.device)    #tensor    on CPU

tensor([1, 2, 3]) cpu


In [ ]:
# move tensor to GPU if available
tensor_GPU = tensor.to(device)
tensor_GPU

tensor([1, 2, 3], device='cuda:0')

In [ ]:
tensor.device

device(type='cpu')

MORE PRACTICE FUNDAMENTALS https://www.learnpytorch.io/00_pytorch_fundamentals/